version: "3.8"
services:
  mysql-flagx0:
    container_name: mysql-flagx0
    image: mysql:5.6
    ports:
      - 4306:3306
    environment:
      - MYSQL_DATABASE=flagdb
      - MYSQL_ROOT_PASSWORD=pass